# -*- coding: utf-8 -*-
"""python_part_assignment_8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WA-2Ng3_uRNYYOfTSFcbc_RU7APS3Lcl
"""

# Exercise 1.

import matplotlib.pyplot as plt

# Data
years = [2010, 2011, 2012, 2013, 2014, 2015, 2016]
City_A = [500000, 550000, 600000, 650000, 700000, 750000, 800000]
City_B = [800000, 850000, 900000, 950000, 1000000, 1050000, 1100000]
City_C = [1000000, 1050000, 1100000, 1150000, 1200000, 1250000, 1300000]
City_D = [1200000, 1250000, 1300000, 1350000, 1400000, 1450000, 1500000]

# Creating line plot
plt.figure(figsize=(10, 6))
plt.plot(years, City_A, label='City A', marker='o')
plt.plot(years, City_B, label='City B', marker='o')
plt.plot(years, City_C, label='City C', marker='o')
plt.plot(years, City_D, label='City D', marker='o')

# Adding Labels, title and legend
plt.xlabel('Year')
plt.ylabel('Population')
plt.title('Population of Cities Over Time')
plt.legend()
plt.show()

# Exercise 2.
import matplotlib.pyplot as plt
import seaborn as sns

# Data
Hours_Studied = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Test_Scores =  [93, 57, 61, 54, 51, 53, 87, 81, 83, 85]

# Creating Scatter plot
plt.figure(figsize=(8, 6))
sns.scatterplot(x=Hours_Studied, y=Test_Scores, color='blue')

# Adding labels and title
plt.xlabel("Hours Studied")
plt.ylabel("Test Scores")
plt.title("Relationship between Hours Studied and Test Scores")
plt.show()

# Exercise 3.

import matplotlib.pyplot as plt

# Data
Month = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
Sales = [11860, 10480, 4997, 5523, 13965, 6011, 13158, 9533, 5158, 9058, 11346, 6675]

# Creating bar chart
plt.figure(figsize=(10, 6))
plt.bar(Month, Sales, color='skyblue')

# Adding labels and title
plt.xlabel("Month")
plt.ylabel("Sales")
plt.title("Total Sales by Month")
plt.show()

